### ISSUE TITLE
Create “production” server and deploy workflow

### ISSUE THREAD

**Issue by jonahroth** [jonahroth/callboard#6]
Where are we going to host this? Can try Heroku or AWS - something we can all deploy to easily. Need a standard way to deploy as well.

**Comment by jonahroth** [comment]
That was easy. We can deploy from GitHub to http://cboard.herokuapp.com. Right now this must be done manually through Heroku but we can set it up automatically once we get comfortable.

**Comment by ParceledTongue** [comment]
Heroku is solid 👌 (I've also used it before, unlike AWS)
